### PR TITLE
#9 add health ecosystem

### PR DESCRIPTION
**Pull request by Emily-Jiang**
Signed-off-by: Emily Jiang <emijiang@uk.ibm.com>

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Does this really need an entire doc to basically say "MP Health Checks can be used for liveness/readiness in Kubernetes, and by extension a Service Mesh"?

Especially as it includes information specific to Health Check that needs to be kept in sync with this if Health Check changes in any way.

I was envisioning something more akin to some kind of table for each of the MP specs outlining some basics of whether it works or doesn't in Service Mesh and only if there's specific things to consider or gotchas to have that information in a separate document.

**Comment by Emily-Jiang** [comment]
@kenfinnigan I think it is better to be researched. As part of this exercise, I feel strongly we need to enhance MP Health to have two endpoints exposed: one for liveness and the other for readiness. It will be a quick overview. It is for sure that we will focus on the gotchas. For the matching areas, it will be a very quick overview.

**Comment by kenfinnigan** [comment]
I'm not saying that the Service Mesh work won't result in changes to Health Check.

What I'm saying is that duplicating Health Spec content in this doc doesn't server any purpose and leads to a maintenance headache.

Related to that, creating separate docs for every spec is unnecessary unless it's more than a paragraph, and I really don't believe this needs to be more than that right now

**Comment by Emily-Jiang** [comment]
ah. You meant to create one .asciidoc for all matching ones. Sure, it is fine. I was thinking about matching to the issues with PRs. I guess I can prune the issues next week by merging the non-problematic ones.

**Comment by kenfinnigan** [comment]
I'm suggesting a single adoc file instead of an adoc file for each spec being referenced from Service Mesh, and that we don't include sub spec content as it gets out of date easily

**Comment by Emily-Jiang** [comment]
ok. It is fine with me. I will sort out the PR soon.

**Comment by Emily-Jiang** [comment]
close this one as I moved the content to the other PR so that all content is in one file.

**Pull request closed without merging**
